name: Rollup Build
on:
  workflow_dispatch:
    inputs:
      environment:
        default: 'build'
        type: choice
        options:
          - build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run rollup
    - uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-build
          path: ./dist
      - run: ls dist
      - name: Pushing to dev branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.BUILD_KEY }}
          branch: rollup-build
          message: Build
          author_name: RollupAction[bot]
          force: true
      - name: create pull request
        run: gh pr create -B main -H rollup-build --title 'Merge rollup-build into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
